rules:
  no-restricted-imports:
    - error
    - patterns:
        - lodash.*
        - modules/50-connectors/*
        - modules/60-gitsync/*
        - modules/70-pipeline/*
        - modules/75-cd/*
        - modules/80-ci/*
        - modules/85-cv/*
        - '@connectors/*'
        - '@gitsync/*'
        - '@pipeline/*'
        - '@cd/*'
        - '@ci/*'
        - '@cv/*'
      paths:
        - lodash
