rules:
  no-restricted-imports:
    - error
    - patterns:
        - lodash.*
        - modules/45-dashboards/*
        - modules/60-gitsync/*
        - modules/70-pipeline/*
        - modules/75-cd/*
        - modules/75-ce/*
        - modules/75-cf/*
        - modules/75-ci/*
        - modules/85-cv/*
        - '@dashboards/*'
        - '@gitsync/*'
        - '@pipeline/*'
        - '@cd/*'
        - '@ce/*'
        - '@cf/*'
        - '@ci/*'
        - '@cv/*'
      paths:
        - lodash
