rules:
  no-restricted-imports:
    - error
    - patterns:
        - lodash.*
      paths:
        - lodash
        - name: yaml
          importNames:
            - stringify
          message: Please use yamlStringify from @common/utils/YamlHelperMethods instead
            of this
