rules:
  no-restricted-imports:
    - error
    - patterns:
        - lodash.*
        - modules/75-cd/*
        - modules/75-cf/*
        - modules/85-cv/*
        - modules/90-ce/*
        - '@cd/*'
        - '@cf/*'
        - '@cv/*'
        - '@ce/*'
      paths:
        - lodash
