rules:
  no-restricted-imports:
    - error
    - patterns:
        - lodash.*
        - modules/75-cd/*
        - modules/80-ci/*
        - modules/85-cv/*
        - '@cd/*'
        - '@ci/*'
        - '@cv/*'
      paths:
        - lodash
