rules:
  no-restricted-imports:
    - error
    - patterns:
        - lodash.*
        - modules/30-secrets/*
        - modules/40-projects-orgs/*
        - modules/50-connectors/*
        - modules/60-gitsync/*
        - modules/70-pipeline/*
        - '@secrets/*'
        - '@projects-orgs/*'
        - '@connectors/*'
        - '@gitsync/*'
        - '@pipeline/*'
      paths:
        - lodash
