name: master
on:
  push:
    branches:
      - master

jobs:
  coverage:
    name: Grouped Code Coverage
    if: ${{ (github.event.pusher.name != 'bot-harness') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Up Node
        uses: actions/setup-node@v1
        with:
          node-version: '13.8'

      - name: Set up GitHub Package Registry token
        run: |
          echo @wings-software:registry=https://npm.pkg.github.com > .npmrc
          echo "//npm.pkg.github.com/:_authToken="$GIT_BOT_TOKEN >> .npmrc
          echo always-auth=true >> .npmrc
        env:
          GIT_BOT_TOKEN: ${{ secrets.GIT_BOT_TOKEN }}

      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install Packages
        run: yarn

      - name: Run tests and coverage
        run: yarn coverage --config jest.coverage.config.js

      - name: Prepare grouped coverage report
        run: |
          npx jest-grouped-coverage -i coverage/coverage-summary.json -c coverage-groups.json -f md
          npx prettier --write coverage/grouped-coverage-report/grouped_summary.md
          mv coverage/grouped-coverage-report/grouped_summary.md COVERAGE.md

      - name: Publish Report
        run: |
          GIT_USER=$(curl --silent -H "Authorization: token ${{ secrets.GIT_BOT_TOKEN }}" -X GET https://api.github.com/user)
          GIT_USER_NAME=$(echo $GIT_USER | tr '\r\n' ' ' | jq -r .name)
          GIT_USER_EMAIL=$(echo $GIT_USER | tr '\r\n' ' ' | jq -r .email)
          git config user.name $GIT_USER_NAME
          git config user.email $GIT_USER_EMAIL
          git add COVERAGE.md
          git commit -m "Update coverage"
          git push -f origin master
